/**
 * Generate TypeScript agent code from ReactFlow nodes/edges
 * @param {Array} nodes - ReactFlow nodes
 * @param {Array} edges - ReactFlow edges
 * @returns {string} Generated agent code
 */
export function generateAgentCode(nodes, edges) {
  const personality = nodes.find(n => n.type === "agentPersonality")?.data || { label: "Sei Agent" };
  const skills = nodes.filter(n => n.type === "skill").map(n => n.data);
  const triggers = nodes.filter(n => n.type === "trigger").map(n => n.data);
  const actions = nodes.filter(n => n.type === "action").map(n => n.data);
  const integrations = nodes.filter(n => n.type === "seiIntegration").map(n => n.data);
  const outputs = nodes.filter(n => n.type === "output").map(n => n.data);

  return `// Auto-generated by SEI No-Code Studio
// Agent: ${personality.label}
// Generated: ${new Date().toISOString()}

import { Agent } from "@elizaos/sdk";
import { GOAT } from "@goat-sdk/sei";

const agent = new Agent({
  name: "${personality.label || "Sei Agent"}",
  personality: "${personality.value || "neutral"}",
  metadata: ${JSON.stringify(personality, null, 2)},
  
  // Skills (${skills.length} configured)
  skills: {
    ${skills.map(s => `"${s.id || s.label}": {
      name: "${s.label}",
      description: "${s.description || 'Auto-generated skill'}",
      execute: async (ctx) => {
        console.log("Executing skill: ${s.label}");
        return { success: true, result: "Skill executed" };
      }
    }`).join(',\n    ')}
  },
  
  // Triggers (${triggers.length} configured)
  triggers: [
    ${triggers.map(t => `{
      type: "${t.id || t.label}",
      name: "${t.label}",
      config: ${JSON.stringify(t.config || {}, null, 4)}
    }`).join(',\n    ')}
  ],
  
  // Actions (${actions.length} configured)
  actions: [
    ${actions.map(a => `{
      name: "${a.id || a.label}",
      description: "${a.description || 'Auto-generated action'}",
      run: async (ctx) => {
        console.log("Running action: ${a.label}");
        // TODO: Implement action logic for ${a.label}
        return { success: true };
      }
    }`).join(',\n    ')}
  ],
  
  // Sei Integrations (${integrations.length} configured)
  integrations: [
    ${integrations.map(i => `{
      type: "${i.id || i.label}",
      name: "${i.label}",
      config: ${JSON.stringify(i.config || {}, null, 4)}
    }`).join(',\n    ')}
  ],
  
  // Output Channels (${outputs.length} configured)
  outputs: [
    ${outputs.map(o => `{
      type: "${o.id || o.label}",
      target: "${o.target || "console"}",
      config: ${JSON.stringify(o.config || {}, null, 4)}
    }`).join(',\n    ')}
  ]
});

// Export for deployment
export default agent;

// Auto-deploy script
if (process.env.AUTO_DEPLOY === "true") {
  (async () => {
    try {
      const goat = new GOAT({ 
        network: process.env.GOAT_NETWORK || "sei-testnet",
        privateKey: process.env.WALLET_PRIVATE_KEY
      });
      
      const result = await goat.deploy(agent);
      console.log("✅ Agent deployed to Sei:", result);
    } catch (error) {
      console.error("❌ Deploy failed:", error);
    }
  })();
}
`;
}