// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uobabgwfoomgnwivlgci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYmFiZ3dmb29tZ253aXZsZ2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODAxMjMsImV4cCI6MjA3MDk1NjEyM30.dhdt5LIiZ9hLyfg1s5UtFtqeV9i0_77uaoXsvjhHEMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});